# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build $(buildConfiguration)'
      inputs:
        command: 'build'
        projects: 'Src/StrongHeart.Features/StrongHeart.Features.csproj'
        arguments: '--configuration $(buildConfiguration) --output ./output'
    
    - task: DotNetCoreCLI@2
      displayName: "Test"
      inputs:
        command: test
        projects: 'Src/StrongHeart.Features.Test/StrongHeart.Features.Test.csproj'
        arguments: '--configuration $(buildConfiguration)'

 #   - task: DotNetCoreCLI@2
 #     displayName: "Publish"
 #     inputs:
 #       command: 'publish'
 #       publishWebProjects: true
 #       arguments: '-r linux-x64 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
 #       zipAfterPublish: true

#   - task: PublishBuildArtifacts@1
#     displayName: "Upload Artifacts"
#     inputs:
#       pathtoPublish: './ouptut' 
#       artifactName: 'StrongHeart artifact' 
  
