using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StrongHeart.DempApp.EfCoreConsole.DataModels.WriteModels{
    /// <summary>
    /// This code is autogenerated by StrongHeart framework and should not contain any handwritten code. 
    /// Dive into this type to change the code generator: 'StrongHeart.EfCore.DesignTimeServices.Scaffold.CustomGenerators.StrongHeartReverseEngineerScaffolder'
    /// </summary>
    [Keyless]
    internal partial class DemoView
    {
        public int Id { get; set; }
    }
}
