using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StrongHeart.DempApp.EfCoreConsole.DataModels.WriteModels{
    /// <summary>
    /// This code is autogenerated by StrongHeart framework and should not contain any handwritten code. 
    /// Dive into this type to change the code generator: 'StrongHeart.EfCore.DesignTimeServices.Scaffold.CustomGenerators.StrongHeartReverseEngineerScaffolder'
    /// </summary>
    [Table("DemoTable")]
    internal partial class DemoTable
    {
        [Key]
        public int Id { get; set; }
        public Guid ExternalId { get; set; }
        [Precision(0)]
        public DateTime CreatedAtUtc { get; set; }
    }
}
