using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StrongHeart.DempApp.EfCoreConsole.DataModels.WriteModels{
    /// <summary>
    /// This code is autogenerated by StrongHeart framework and should not contain any handwritten code. 
    /// Dive into this type to change the code generator: 'StrongHeart.EfCore.DesignTimeServices.Scaffold.CustomGenerators.StrongHeartReverseEngineerScaffolder'
    /// </summary>
    [Keyless]
    [Table("VersionInfo")]
    internal partial class VersionInfo
    {
        public long Version { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AppliedOn { get; set; }
        [StringLength(1024)]
        public string? Description { get; set; }
    }
}
