using Microsoft.EntityFrameworkCore;
using StrongHeart.EfCore;
using StrongHeart.DempApp.EfCoreConsole.DataModels.WriteModels;
using StrongHeart.DempApp.EfCoreConsole.DataModels.Context;
using System;

namespace StrongHeart.DempApp.EfCoreConsole.DataModels.Context{
    /// <summary>
    /// This code is autogenerated by StrongHeart framework and should not contain any handwritten code. 
    /// Dive into this type to change the code generator: 'StrongHeart.EfCore.DesignTimeServices.Scaffold.CustomGenerators.StrongHeartReverseEngineerScaffolder'
    /// </summary>
    partial class MyDemoContext
    {


        //This method will ensure that the stored procedure read models don't NEED to have a primary key returned. Read the doc for details.
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {

        }
    }
}