name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.cmd'
      - '**/*.cake'
      - '**/*.json'
      - '**/*.archimate'
      - '**/*.gitignore'
      - '**/*.gitattributes'      
    branches:    
      - master
      - 'feature/**'
      - 'bugfix/**'
      - 'release/**'

env:  
    
  Sha: ${{ github.sha }}

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'    
    
    - name: Run CI Build via Cake
      run: dotnet run --project ./Build/StrongHeart.Build/StrongHeart.Build.csproj --target BuildStrongHeart